name: Deploy to Kubernetes
on:
  push:
    branches:
      - feature/github_actions_kubernetes2
jobs:
  deploy:
    name: Build Publish Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets. DOCKER_PASSWORD	}}
      - name: Build Image
        run: docker build  -t hughdo/examreg-idfsg-fe:${{ github.sha }} .
      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REGISTRY_URL }}:${{ github.sha }}
      - name: Azure Login
        run: az login --service-principal --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT }}
      - name: Set Kubeconfig
        run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_CLUSTER_NAME }}
      - name: Get Kubeconfig
        run: cat ~/.kube/config
      - name: Set Image Tag
        run: sed -i 's|GITHUB_SHA|${{ github.sha }}|' ./k8s/deployment.yml
      - name: Check yaml file
        run: grep -E "image" ./k8s/deployment.yml
      - name: Apply yaml file
        run: kubectl apply -f ./k8s/deployment.yml
      - name: Check result
        run: kubectl get all
