name: Deploy to Kubernetess
on:
    push:
        branches:
            - master
jobs:
    deploy:
        name: Build Publish Deploy FE
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1
            - name: Docker Login
              run:
                  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{
                  secrets.DOCKER_PASSWORD	}}
            - name: Build Image
              run:
                  docker build  -t ${{ secrets.DOCKER_USERNAME }}/${{
                  secrets.DOCKER_REGISTRY_URL }}:${{ github.sha }} .
            - name: Push Image
              run:
                  docker push ${{ secrets.DOCKER_USERNAME }}/${{
                  secrets.DOCKER_REGISTRY_URL }}:${{ github.sha }}
            - name: DigitalOcean auth init
              run: doctl auth init -t ${{secrets.DIGITALOCEAN_TOKEN}}
            - name: Set Kubeconfig
              run:
                  doctl kubernetes cluster kubeconfig save
                  ${{secrets.CLUSTER_NAME}}
            - name: Get Kubeconfig
              run: cat ~/.kube/config
            - name: Set Image Tag
              run: sed -i 's|GITHUB_SHA|${{ github.sha }}|' ./k8s/deployment.yml
            - name: Check yaml file
              run: grep -E "image" ./k8s/deployment.yml
            - name: Apply yaml file
              run: kubectl apply -f ./k8s/deployment.yml
            - name: Check result
              run: kubectl get all
