name: Exam Reg
on:
  push:
    branches:
      - feature/github_actions_docker
jobs:
  publish:
    name: Publish image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Login
        run: docker login -u ${{secrets.DOCKER_USERNAME }} -p ${{secrets. DOCKER_PASSWORD	}}
      - name: Build Image
        run: docker build  -t hughdo/examreg-idfsg-fe:${{github.sha}} .
      - name: Push Image
        run: docker push hughdo/examreg-idfsg-fe:${{github.sha}}
