name: Azure test
on:
  push:
    branches:
      - feature/github_actions_azure
jobs:
  kubeconfig:
    name: Set kube config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Login
        run: az login --service-principal --username ${{secrets.AZURE_USERNAME}} --password ${{secrets.AZURE_PASSWORD}} --tenant ${{secrets.AZURE_TENANT}}
      - name: Set Kubeconfig
        run: az aks get-credentials --resource-group ${{secrets.AZURE_RESOURCE_GROUP}} --name ${{secrets.AZURE_CLUSTER_NAME}}
      - name: Get Kubeconfig
        run: cat ~/.kube/config
      - name: Test kubectl
        run: kubectl get all
